---
title: "Waterplanten en waterkwaliteit"
subtitle: "Een verkenning"
format: html
code-fold: show
warning: false
message: false
---

## Verbinden met de database

```{r}
library(magrittr)
library(arrow)
library(dplyr)
```



```{r}

```

## Weergave tabellen

```{r}
tabellen <- list.files("../data-raw/parquet", full.names = TRUE)

tabellen <- tabellen[stringr::str_detect(basename(tabellen), "^\\d", negate = TRUE)]

print(stringr::str_remove(basename(tabellen), "\\.parquet"))

purrr::walk(tabellen, 
            \(tabelnaam) {
              print(paste("Tabelnaam: ", basename(tabelnaam)))
              
              tabel <- open_dataset(tabelnaam)
              
              tabel %>% 
                dplyr::collect() %>% 
                dplyr::glimpse()
            })

```


## Kaart met locaties

```{r}
library(sf)
library(leaflet)
library(dplyr)

# locs <- dplyr::tbl(con, "Locations")

open_dataset("../data-raw/parquet/Locations.parquet") %>%  
  dplyr::collect() %>% 
  dplyr::filter(!is.na(x_rd)) %>% 
  sf::st_as_sf(coords = c("x_rd", "y_rd"), crs = 28992, remove = FALSE) %>%  
  sf::st_transform(crs = 4326) %>%  
  leaflet() %>%  
  addTiles()  %>%  
  addCircleMarkers(label = ~paste(location_name, landscape_nl), 
                   stroke = FALSE, fillOpacity = 0.9)



```


```{r}
# odbc::dbDisconnect(con)
sessioninfo::session_info()
```


